package com.bank.esrdcy212mainframepricerreleasefiles;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Generated by CobolIQ from d:\cobol\ESRDCY212MainframePricerReleaseFiles
 * 21 programs, 232 paragraphs, 699 return codes
 */
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
