"""
Package init - auto-generated from COBOL program `ESCAL056`.

Source: ESCAL056
Generated by: snapshot-maker COBOL port generator.
DO NOT EDIT MANUALLY - re-generate from source instead.
"""

__cobol_program__ = "ESCAL056"
__source_file__ = "ESCAL056"
__paragraphs__ = 8
__return_codes__ = 9
__state_machines__ = 0
__copybooks__ = ["BILLCPY", "WAGECPY"]

from . import enums, return_codes, tables, io_contract, paragraphs, pricer_engine  # noqa: F401
