"""
State machine enums (88-level COBOL conditions) - auto-generated from COBOL program `ESCAL056`.

Source: ESCAL056
Generated by: snapshot-maker COBOL port generator.
DO NOT EDIT MANUALLY - re-generate from source instead.
"""

from enum import Enum

# (no 88-level state machines found in this program)
