"""
Return-code catalog (Trigger Summary) - auto-generated from COBOL program `ESCAL056`.

Source: ESCAL056
Generated by: snapshot-maker COBOL port generator.
DO NOT EDIT MANUALLY - re-generate from source instead.
"""

from dataclasses import dataclass
from typing import List, Optional

@dataclass(frozen=True)
class ReturnCodeSpec:
    value: str
    variable: str
    paragraph: str
    condition: Optional[str]
    line: int

RETURN_CODES: List[ReturnCodeSpec] = [
    ReturnCodeSpec(value="52", variable="PPS-RTC", paragraph="0100-INITIAL-ROUTINE", condition="P-PROV-TYPE = '41'", line=188),
    ReturnCodeSpec(value="53", variable="PPS-RTC", paragraph="1000-EDIT-THE-BILL-INFO", condition="P-SPEC-PYMT-IND NOT = '1' AND ' '", line=221),
    ReturnCodeSpec(value="54", variable="PPS-RTC", paragraph="1000-EDIT-THE-BILL-INFO", condition="(B-DOB-DATE = ZERO) OR (B-DOB-DATE NOT NUMERIC)", line=227),
    ReturnCodeSpec(value="55", variable="PPS-RTC", paragraph="1000-EDIT-THE-BILL-INFO", condition="(B-PATIENT-WGT = 0) OR (B-PATIENT-WGT NOT NUMERIC)", line=233),
    ReturnCodeSpec(value="56", variable="PPS-RTC", paragraph="1000-EDIT-THE-BILL-INFO", condition="(B-PATIENT-HGT = 0) OR (B-PATIENT-HGT NOT NUMERIC)", line=239),
    ReturnCodeSpec(value="57", variable="PPS-RTC", paragraph="1000-EDIT-THE-BILL-INFO", condition="B-REV-CODE = '0821' OR '0831' OR '0841' OR '0851' OR '0880' OR '0881' NEXT SENTENCE", line=245),
    ReturnCodeSpec(value="58", variable="PPS-RTC", paragraph="1000-EDIT-THE-BILL-INFO", condition="B-COND-CODE NOT = '73' AND '74' AND ' '", line=254),
    ReturnCodeSpec(value="71", variable="PPS-RTC", paragraph="1000-EDIT-THE-BILL-INFO", condition="B-PATIENT-HGT > 300.00", line=260),
    ReturnCodeSpec(value="72", variable="PPS-RTC", paragraph="1000-EDIT-THE-BILL-INFO", condition="B-PATIENT-WGT > 500.00", line=266),
]

# Convenience constants - RC_<VALUE>_<VAR_SHORT>
RC_52_PPS = "52"
RC_53_PPS = "53"
RC_54_PPS = "54"
RC_55_PPS = "55"
RC_56_PPS = "56"
RC_57_PPS = "57"
RC_58_PPS = "58"
RC_71_PPS = "71"
RC_72_PPS = "72"

# Catalog: value -> number of emission sites
RC_CATALOG = {
    "52": 1,
    "53": 1,
    "54": 1,
    "55": 1,
    "56": 1,
    "57": 1,
    "58": 1,
    "71": 1,
    "72": 1,
}
